### ISSUE TITLE
Slideshow Stops Transitionining

### ISSUE THREAD

**Issue by samhinsh** [zvonicek/ImageSlideshow#138] opened 2017-04-11 04:32 UTC
Hi, I'm using the slideshow and it only makes one transition for me (regardless of the time interval I've set, or how many images I've loaded in the input array). I have the slideshow in multiple places in my app, and this happens in every single place. I've tried mirroring the example given as closely as possible. 

Thanks!

**Comment by zvonicek** [comment] 2017-05-01 09:30
Hi! Could you please share your example project? I haven't experienced this issue before and cannot reproduce it on my side.

**Comment by Mbt925** [comment] 2017-05-13 05:44
I've encountered this problem too.

`self.slideShow.setImageInputs(slideImages)
        self.slideShow.contentScaleMode = .scaleAspectFill
        self.slideShow.slideshowInterval = 500
        self.slideShow.zoomEnabled = true
        self.slideShow.pageControlPosition = .hidden
        self.slideShow.activityIndicator = DefaultActivityIndicator(style: .whiteLarge, color: .black)`

**Comment by zvonicek** [comment] 2017-05-17 18:43
@Mbt925 I'm sorry I still can't see the problem. I tried your code but automatic transition works correctly there...

**Comment by Mbt925** [comment] 2017-05-17 18:47
I am using AlamofireSource.

**Comment by zvonicek** [comment] 2017-05-17 18:52
I've been trying it with AlamofireSource too. Ideally, send me an example project demonstrating the problem and I'll look into it.

**Comment by Mbt925** [comment] 2017-05-18 05:19
I assumed `slideshowInterval` was in milliseconds (`self.slideShow.slideshowInterval = 500`). But it seems it's in seconds. Am I correct?

**Comment by scottcc** [comment] 2017-05-18 13:31
`NSTimeInterval` is indeed seconds (use fractions for sub-seconds). Sounds like you have found the root issue there.

**Comment by zvonicek** [comment] 2017-05-20 18:08
Oh, `slideshowInterval` is indeed in seconds. Sorry for the confusion, it's my fault it was not explicitly mentioned in the docs. Fixed it. 
I think I can now close the issue, let me know if there are any further issues.

**Closed by zvonicek** 2017-05-20 18:08 UTC
