### ISSUE TITLE
Image slide show crashing when image is opened in full screen mode.

### ISSUE THREAD

**Issue by saitejapanditi67** [zvonicek/ImageSlideshow#357] opened 2019-10-28 07:21 UTC
Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan 333.5]

**Comment by nvelichkin** [comment] 2019-11-12 09:30
@saitejapanditi67 Fork this library and update `presentFullScreenController` method. Add modal presentation style to `fulscreen` object

`fullscreen.modalPresentationStyle = .fullScreen`

**Comment by thihaaung6245** [comment] 2020-01-01 06:06
@nvelichkin, is it the real solution?

**Comment by zvonicek** [comment] 2020-01-19 21:14
Hi, can anyone include the symbolicated stacktrace of this crash?

**Comment by nvelichkin** [comment] 2020-01-20 14:30
> @nvelichkin, is it the real solution?

Yes, it allows to workaround this issue

**Comment by saitejapanditi67** [comment] 2020-02-24 05:50
> Hi, can anyone include the symbolicated stacktrace of this crash?

2020-02-24 11:18:56.083823+0530 Rev Your Soul[3263:35716] *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [207 nan]. Layer: <CALayer:0x600000e3e440; position = CGPoint (207 235.667); bounds = CGRect (0 0; 364 364); delegate = <UIImageView: 0x7fdc32fb6800; frame = (25 53.6667; 364 364); clipsToBounds = YES; opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x600000e3e440>>; masksToBounds = YES; allowsGroupOpacity = YES; >'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23baa1ee __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50864b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23baa02c +[NSException raise:format:] + 188
	3   QuartzCore                          0x00007fff2b078e67 _ZN2CA5Layer12set_positionERKNS_4Vec2IdEEb + 187
	4   QuartzCore                          0x00007fff2b0682f9 -[CALayer setPosition:] + 49
	5   QuartzCore                          0x00007fff2b06899e -[CALayer setFrame:] + 563
	6   UIKitCore                           0x00007fff47a346ca -[UIView(Geometry) setFrame:] + 421
	7   UIKitCore                           0x00007fff479fe124 -[UIImageView _setViewGeometry:forMetric:] + 161
	8   ImageSlideshow                      0x000000010e2b31d8 $s14ImageSlideshow14ZoomInAnimatorC17animateTransition5usingySo36UIViewControllerContextTransitioning_p_tFyycfU_Tf2nnin_n + 808
	9   ImageSlideshow                      0x000000010e28b08d $sIeg_IeyB_TR + 45
	10  UIKitCore                           0x00007fff47a463fe +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:] + 528
	11  UIKitCore                           0x00007fff47a46849 +[UIView(UIViewAnimationWithBlocks) animateWithDuration:delay:usingSpringWithDamping:initialSpringVelocity:options:animations:completion:] + 178
	12  ImageSlideshow                      0x000000010e2b2d11 $s14ImageSlideshow14ZoomInAnimatorC17animateTransition5usingySo36UIViewControllerContextTransitioning_p_tF + 7537
	13  ImageSlideshow                      0x000000010e2b3920 $s14ImageSlideshow14ZoomInAnimatorC17animateTransition5usingySo36UIViewControllerContextTransitioning_p_tFTo + 64
	14  UIKitCore                           0x00007fff46f37bda ___UIViewControllerTransitioningRunCustomTransition_block_invoke_2 + 54
	15  UIKitCore                           0x00007fff4704e665 +[UIInputResponderController _pinInputViewsForInputResponderController:onBehalfOfResponder:duringBlock:] + 99
	16  UIKitCore                           0x00007fff46f37b6e ___UIViewControllerTransitioningRunCustomTransition_block_invoke.645 + 180
	17  UIKitCore                           0x00007fff47a44969 +[UIView(Animation) _setAlongsideAnimations:toRunByEndOfBlock:] + 175
	18  UIKitCore                           0x00007fff46f379f4 _UIViewControllerTransitioningRunCustomTransition + 553
	19  UIKitCore                           0x00007fff46e1a529 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.467 + 2632
	20  UIKitCore                           0x00007fff47581d46 _runAfterCACommitDeferredBlocks + 352
	21  UIKitCore                           0x00007fff47572774 _cleanUpAfterCAFlushAndRunDeferredBlocks + 248
	22  UIKitCore                           0x00007fff475a2374 _afterCACommitHandler + 85
	23  CoreFoundation                      0x00007fff23b0c667 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	24  CoreFoundation                      0x00007fff23b070fe __CFRunLoopDoObservers + 430
	25  CoreFoundation                      0x00007fff23b0777a __CFRunLoopRun + 1514
	26  CoreFoundation                      0x00007fff23b06e66 CFRunLoopRunSpecific + 438
	27  GraphicsServices                    0x00007fff38346bb0 GSEventRunModal + 65
	28  UIKitCore                           0x00007fff47578dd0 UIApplicationMain + 1621
	29  Rev Your Soul                       0x000000010bb379ab main + 75
	30  libdyld.dylib                       0x00007fff516ecd29 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by saitejapanditi67** [comment] 2020-02-24 06:33
> @saitejapanditi67 Fork this library and update `presentFullScreenController` method. Add modal presentation style to `fulscreen` object
> 
> `fullscreen.modalPresentationStyle = .fullScreen`

again getting same error.

**Comment by zvonicek** [comment] 2020-06-21 13:22
A duplicate of #357, should be fixed in d5db87e.

**Closed by zvonicek** 2020-06-21 13:22 UTC
