### ISSUE TITLE
Fullscreen initial image bug when slideshow is not circular

### ISSUE THREAD

**Issue by rx2130** [zvonicek/ImageSlideshow#67] opened 2016-09-29 16:10 UTC
When I have multiple images in my slideshow and set `slideshow.circular = false`, then click on an image to present in full screen would not present the current image I tapped. It would actually load the previous image! So I guess the index of the initial image is not set properly when the full screen is presented. 

Forget to mention I'm using the **swift-3** branch :)

**Comment by zvonicek** [comment] 2016-10-03 21:34
Hi, thanks for your report! I'll look into that.

**Comment by adamfraser** [comment] 2016-10-11 16:49
Getting this same issue on version 0.6

**Comment by adamfraser** [comment] 2016-10-11 18:21
I can fix this by setting 'circular' to false on the FullScreenSlideshowViewController's 'slideshow' property.

eg using the example from the Readme:
`ctr.slideshow.circular = false`

Maybe setting circular to false on an ImageSlideshow instance should do the same for a FullScreenSlideshowViewController? At the moment they don't really know about each other so might take some refactoring. I can also see users wanting to have circular enabled on one and not in the other.

**Comment by zvonicek** [comment] 2016-10-16 12:55
The problem was caused by using `scrollViewPage` in FullScreenSlideshowVC, which is not consistent if one slideshow is circular and other is not. I fixed it by changing that to `currentPage`, which preserves such consistency.

This change however breaks backward compatibility so I cannot push it straight away to `swift-3` branch, which is currently used by some users but not CocoaPods-versioned. It's therefore just in `swift-3-dev` for now and will be part of 1.0 release that's hopefully comming soon.

**Comment by rx2130** [comment] 2016-10-21 21:09
Just checked the `swift-3-dev`. It fixed the previous bug yet introduced another new one.

FullScreenSlideshowVC now opens at the same index as the current imageSlide. But when FullScreenSlideshowVC dismiss, the imageSlide slide current index is one behind the correct index.

**Comment by zvonicek** [comment] 2016-10-23 15:28
Note that you also need to change your `pageSelected` closure and call `setCurrentPage` instead of `setScrollViewPage`. Check my change in sample project in 9e88e08.

**Closed** 2016-10-29 18:17 UTC
Labels: bug
