### ISSUE TITLE
AspectFill not working

### ISSUE THREAD

**Issue by SMFakhir** [zvonicek/ImageSlideshow#56] opened 2016-09-07 15:18 UTC
AspectFill is not working when using remote input source.

**Comment by javierdac** [comment] 2016-10-25 20:33
Are you planning to correct this bug in the next release?

**Comment by yamifr07** [comment] 2016-10-26 02:09
Any update?

**Comment by yamifr07** [comment] 2016-10-27 02:29
In my case the bug occurred when I used an input source that fetch image from url (using haneke). The problem is that the library first instantiates ImageSlideshowItem and then set contentMode, so calls setToImageView before setting scale mode:
`let item = ImageSlideshowItem(image: image, zoomEnabled: self.zoomEnabled)            item.imageView.contentMode = self.contentScaleMode`
In my case, I solved it sending scale mode to my input source and set it to imageView inside setToImageView method before setting image.
I think the right solution is to send contentMode to ImageSlideshowItem constructor and set it before calling setToImageView

**Comment by zvonicek** [comment] 2016-10-28 16:05
@yamifr07 Thanks for your post. I struggle with reproducing the issue but if the problem really is in setting contentMode after loading image, this should be already fixed in `swift-3-dev` branch and next release. I made major changes in loading mechanism to make lazy-loading possible so the load is not triggered in `ImageSlideshowItem` `init()` anymore.

If you have few minutes to spare, I'd be glad if you could test if the issue was resolved.

**Closed** 2016-12-04 13:04 UTC
Labels: bug

**Comment by deya-eldeen** [comment] 2022-02-05 21:00
this works for me:
            self.slideShow?.contentScaleMode = .scaleAspectFill
